import { contextBridge, ipcRenderer, type IpcRendererEvent } from "electron";
import type { AppUpdateState, PiApi, PiEvent } from "../shared/protocol.js";

const api: PiApi = {
  getSnapshot: () => ipcRenderer.invoke("pi:getSnapshot"),
  chooseWorkspace: () => ipcRenderer.invoke("pi:chooseWorkspace"),
  chooseFile: () => ipcRenderer.invoke("pi:chooseFile"),
  chooseAttachmentFiles: () => ipcRenderer.invoke("pi:chooseAttachmentFiles"),
  persistImageAttachment: (input) => ipcRenderer.invoke("pi:persistImageAttachment", input),
  loadImagePreview: (path) => ipcRenderer.invoke("pi:loadImagePreview", path),
  startSession: (options) => ipcRenderer.invoke("pi:startSession", options),
  focusSession: (sessionKey, opts) => ipcRenderer.invoke("pi:focusSession", sessionKey, opts),
  disposeSession: (sessionKey) => ipcRenderer.invoke("pi:disposeSession", sessionKey),
  loadOlder: (options) => ipcRenderer.invoke("pi:loadOlder", options),
  listLiveSessions: () => ipcRenderer.invoke("pi:listLiveSessions"),
  prompt: (text, opts) => ipcRenderer.invoke("pi:prompt", text, opts),
  steer: (text, opts) => ipcRenderer.invoke("pi:steer", text, opts),
  followUp: (text, opts) => ipcRenderer.invoke("pi:followUp", text, opts),
  undoFileChange: (path, opts) => ipcRenderer.invoke("pi:undoFileChange", path, opts),
  editFollowUp: (index, text, opts, expectedText) => ipcRenderer.invoke("pi:editFollowUp", index, text, opts, expectedText),
  sendFollowUpNow: (index, opts, expectedText) => ipcRenderer.invoke("pi:sendFollowUpNow", index, opts, expectedText),
  abort: (opts) => ipcRenderer.invoke("pi:abort", opts),
  newSession: (opts) => ipcRenderer.invoke("pi:newSession", opts),
  resumeSession: (sessionPath) => ipcRenderer.invoke("pi:resumeSession", sessionPath),
  forkSession: (entryId) => ipcRenderer.invoke("pi:forkSession", entryId),
  cloneSession: () => ipcRenderer.invoke("pi:cloneSession"),
  importSession: (path, cwdOverride) => ipcRenderer.invoke("pi:importSession", path, cwdOverride),
  compact: (instructions) => ipcRenderer.invoke("pi:compact", instructions),
  setThinkingLevel: (level) => ipcRenderer.invoke("pi:setThinkingLevel", level),
  setMode: (mode, opts) => ipcRenderer.invoke("pi:setMode", mode, opts),
  setModeProfile: (mode, profile, opts) => ipcRenderer.invoke("pi:setModeProfile", mode, profile, opts),
  listPlans: (opts) => ipcRenderer.invoke("pi:listPlans", opts),
  readPlan: (planId, opts) => ipcRenderer.invoke("pi:readPlan", planId, opts),
  updatePlan: (planId, content, revision, opts) => ipcRenderer.invoke("pi:updatePlan", planId, content, revision, opts),
  savePlan: (title, content, status, planId, opts) => ipcRenderer.invoke("pi:savePlan", title, content, status, planId, opts),
  startExecution: (planId, opts) => ipcRenderer.invoke("pi:startExecution", planId, opts),
  setTools: (tools, opts) => ipcRenderer.invoke("pi:setTools", tools, opts),
  setSkills: (patterns) => ipcRenderer.invoke("pi:setSkills", patterns),
  reload: () => ipcRenderer.invoke("pi:reload"),
  executeCommand: (name, args) => ipcRenderer.invoke("pi:executeCommand", name, args),
  setModel: (model) => ipcRenderer.invoke("pi:setModel", model),
  getCommands: () => ipcRenderer.invoke("pi:getCommands"),
  getModels: () => ipcRenderer.invoke("pi:getModels"),
  getTools: () => ipcRenderer.invoke("pi:getTools"),
  getResources: () => ipcRenderer.invoke("pi:getResources"),
  getSessionTree: () => ipcRenderer.invoke("pi:getSessionTree"),
  resolveTrust: (trusted) => ipcRenderer.invoke("pi:resolveTrust", trusted),
  getGitBranch: (cwd) => ipcRenderer.invoke("pi:getGitBranch", cwd),
  listProjects: () => ipcRenderer.invoke("pi:listProjects"),
  addProject: (path) => ipcRenderer.invoke("pi:addProject", path),
  selectProject: (projectId) => ipcRenderer.invoke("pi:selectProject", projectId),
  setActiveProject: (projectId) => ipcRenderer.invoke("pi:setActiveProject", projectId),
  removeProject: (projectId) => ipcRenderer.invoke("pi:removeProject", projectId),
  revealInFolder: (path) => ipcRenderer.invoke("pi:revealInFolder", path),
  openFile: (path) => ipcRenderer.invoke("pi:openFile", path),
  listSessions: (cwd) => ipcRenderer.invoke("pi:listSessions", cwd),
  listProjectFiles: (cwd) => ipcRenderer.invoke("pi:listProjectFiles", cwd),
  renameSession: (sessionPath, name) => ipcRenderer.invoke("pi:renameSession", sessionPath, name),
  deleteSession: (sessionPath) => ipcRenderer.invoke("pi:deleteSession", sessionPath),
  getSessionContext: (sessionPath) => ipcRenderer.invoke("pi:getSessionContext", sessionPath),
  listProviders: () => ipcRenderer.invoke("pi:listProviders"),
  getProviderUsage: (options) => ipcRenderer.invoke("pi:getProviderUsage", options),
  loginWithApiKey: (providerId, apiKey) => ipcRenderer.invoke("pi:loginWithApiKey", providerId, apiKey),
  logoutProvider: (providerId) => ipcRenderer.invoke("pi:logoutProvider", providerId),
  loginWithOAuth: (providerId) => ipcRenderer.invoke("pi:loginWithOAuth", providerId),
  answerAuthPrompt: (promptId, answer) => ipcRenderer.invoke("pi:answerAuthPrompt", promptId, answer),
  cancelProviderLogin: (providerId) => ipcRenderer.invoke("pi:cancelProviderLogin", providerId),
  openExternal: (url) => ipcRenderer.invoke("pi:openExternal", url),
  indexStatus: (cwd) => ipcRenderer.invoke("pi:indexStatus", cwd),
  indexRefresh: (cwd) => ipcRenderer.invoke("pi:indexRefresh", cwd),
  indexSearch: (cwd, query, opts) => ipcRenderer.invoke("pi:indexSearch", cwd, query, opts),
  indexFindUsages: (cwd, qualified, opts) => ipcRenderer.invoke("pi:indexFindUsages", cwd, qualified, opts),
  getMcpConfig: (cwd) => ipcRenderer.invoke("pi:getMcpConfig", cwd),
  setMcpServerEnabled: (name, enabled) => ipcRenderer.invoke("pi:setMcpServerEnabled", name, enabled),
  importCursorMcp: () => ipcRenderer.invoke("pi:importCursorMcp"),
  openMcpConfigFile: (cwd) => ipcRenderer.invoke("pi:openMcpConfigFile", cwd),
  getUpdateState: () => ipcRenderer.invoke("pi:getUpdateState"),
  checkForUpdate: () => ipcRenderer.invoke("pi:checkForUpdate"),
  downloadUpdate: () => ipcRenderer.invoke("pi:downloadUpdate"),
  installUpdate: () => ipcRenderer.invoke("pi:installUpdate"),
  onUpdateState: (listener) => {
    const handler = (_event: IpcRendererEvent, state: unknown) => listener(state as AppUpdateState);
    ipcRenderer.on("pi:updateState", handler);
    return () => ipcRenderer.removeListener("pi:updateState", handler);
  },
  http: {
    workspace: (projectId) => ipcRenderer.invoke("pi:http:workspace", projectId),
    readFile: (projectId, relativePath) => ipcRenderer.invoke("pi:http:readFile", projectId, relativePath),
    saveFile: (projectId, relativePath, content) => ipcRenderer.invoke("pi:http:saveFile", projectId, relativePath, content),
    readEnvironment: (projectId, relativePath) => ipcRenderer.invoke("pi:http:readEnvironment", projectId, relativePath),
    saveEnvironment: (projectId, relativePath, content) => ipcRenderer.invoke("pi:http:saveEnvironment", projectId, relativePath, content),
    createFolder: (projectId, parentPath, name) => ipcRenderer.invoke("pi:http:createFolder", projectId, parentPath, name),
    createFile: (projectId, parentPath, name) => ipcRenderer.invoke("pi:http:createFile", projectId, parentPath, name),
    createEnvironment: (projectId, name) => ipcRenderer.invoke("pi:http:createEnvironment", projectId, name),
    listRuns: (projectId, scopePath) => ipcRenderer.invoke("pi:http:listRuns", projectId, scopePath),
    readRun: (projectId, scopePath, runId) => ipcRenderer.invoke("pi:http:readRun", projectId, scopePath, runId),
    readResponse: (projectId, scopePath, runId, requestId) => ipcRenderer.invoke("pi:http:readResponse", projectId, scopePath, runId, requestId),
    deleteRun: (projectId, scopePath, runId) => ipcRenderer.invoke("pi:http:deleteRun", projectId, scopePath, runId),
    deleteResponse: (projectId, scopePath, runId, requestId) => ipcRenderer.invoke("pi:http:deleteResponse", projectId, scopePath, runId, requestId),
    deleteRunHistory: (projectId, scopePath) => ipcRenderer.invoke("pi:http:deleteRunHistory", projectId, scopePath),
    run: (projectId, scopePath, environmentName, requestLine) => ipcRenderer.invoke("pi:http:run", projectId, scopePath, environmentName, requestLine),
  },
  onEvent: (listener) => {
    const handler = (_event: Electron.IpcRendererEvent, payload: PiEvent) => listener(payload);
    ipcRenderer.on("pi:event", handler);
    return () => ipcRenderer.removeListener("pi:event", handler);
  },
};

contextBridge.exposeInMainWorld("pi", api);
